# Site settings
title: Vesterheim Norwegian-American Museum 
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://vesterheim.github.io"
twitter_username: jekyllrb
github_username:  jekyll

timezone: America/Chicago
exclude: 
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - node_modules
  - package.json

collections:
  norway-tours--guides:
    output: false

gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
permalink: pretty
# setting a part of the has doesn't work. Either it set the whole hash or none. For example navigation['exclude'] = true
# won't be set if there is a navigation['order'] = 10 in the front matter. IS this a bug to raise? I couldn't figure out
# how to change the behaviour just by looking at the source.
defaults:
  -
    scope:
      type: pages
    values:
      layout: page 
      show_social_sharing_bar: true 
  -
    scope:
      type: posts
    values:
#      permalink: /events/calendar/:year/:month/:day/:title/ # I wish this worked as I had expected as a default
      categories: events calendar # Ugly hack: don't touch!
      layout: post
      calendar__include: true
      navigation:
        exclude: true
  -
    scope:
      path: events/calendar
    values:
      calendar__include: true
  -
    scope:
      path: folk-art-school
    values:
      css_theme: theme--folk-art
  -
    scope:
      path: folk-art-school/instructors
    values:
      layout: instructor
      navigation:
        exclude: true
  -
    scope:
      path: folk-art-school/classes
    values:
      layout: class
      navigation:
        exclude: true
# The scoping is correct, but see about about setting the navigation hash
#  -
#    scope:
#      path: exhibitions/open-air
#      type: pages
#    values:
#      navigation:
#        exclude: true 
#  -  
#    scope:
#      path: join-give/recognition/profiles
#      type: pages
#    values:
#      navigation:
#        exclude: true 
#  -
#    scope:
#      path: join-give/recognition/valhalla-society/profiles
#      type: pages
#    values:
#      navigation:
#        exclude: true        

#permalink: /events/calendar/:year/:month/:day/:title/
#permalink: /:path/:year/:month/:day/:title/

# Markdown Processors
kramdown:
#  input:         kramdown
#  hard_wrap:     true
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
  image: 
    source: assets/images/_fullsize
    output: generated
    presets:
      # Proportional preset
      users:
        attr:
          class: user-portrait
          itemprop: image
        width: 350
      # Scaled and cropped preset
      half:
        width: 400
      height: 400

monthly_archive:
  path: events/calendar/
daily_archive:
  path: events/calendar/
yearly_archive:
  path: events/calendar/

picture:
  source: assets/_images--fullsize
  output: assets/images
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5, 2]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 64em)"
        width: 746
      source_med1:
        media: "(min-width: 59em) and (max-width: 63.9375em)"
        width: 706
      source_med2:
        media: "(min-width: 55em) and (max-width: 58.9375em)"
        width: 628
      source_med3:
        media: "(min-width: 50em) and (max-width: 54.9375em)"
        width: 560
      source_med4:
        media: "(min-width: 42em) and (max-width: 49.9375em)"
        width: 486
      source_med5:
        media: "(min-width: 40em) and (max-width: 41.9375em)"
        width: 416
      source_med6:
        media: "(min-width: 38em) and (max-width: 39.9375em)"
        width: 628
      source_med7:
        media: "(min-width: 33em) and (max-width: 37.9375em)"
        width: 560
      source_med8:
        media: "(min-width: 28em) and (max-width: 32.9375em)"
        width: 486
      source_med9:
        media: "(min-width: 21em) and (max-width: 27.9375em)"
        width: 416
      source_default:
        width: 320      
    # Home Page Panel Images
    panel:
      ppi: [1, 1.5, 2]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 64em)"
        width: 490
      source_med1:
        media: "(min-width: 59em) and (max-width: 63.9375em)"
        width: 465
      source_med2:
        media: "(min-width: 55em) and (max-width: 58.9375em)"
        width: 376
      source_med3:
        media: "(min-width: 50em) and (max-width: 54.9375em)"
        width: 348
      source_med4:
        media: "(min-width: 42em) and (max-width: 49.9375em)"
        width: 312
      source_med5:
        media: "(min-width: 40em) and (max-width: 41.9375em)"
        width: 204
      source_med6:
        media: "(min-width: 38em) and (max-width: 39.9375em)"
        width: 608
      source_med7:
        media: "(min-width: 33em) and (max-width: 37.9375em)"
        width: 576
      source_med8:
        media: "(min-width: 28em) and (max-width: 32.9375em)"
        width: 496
      source_med9:
        media: "(min-width: 21em) and (max-width: 27.9375em)"
        width: 432
      source_default:
        width: 320  
    # Home Page Panel Images
    carousel:
      ppi: [1, 1.5, 2]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 64em)"
        height: 432
        width: 1200
      source_med1:
        media: "(min-width: 59em) and (max-width: 63.9375em)"
        height: 432
        width: 1200
      source_med2:
        media: "(min-width: 55em) and (max-width: 58.9375em)"
        height: 432
        width: 1200
      source_med3:
        media: "(min-width: 50em) and (max-width: 54.9375em)"
        height: 432
        width: 1200
      source_med4:
        media: "(min-width: 42em) and (max-width: 49.9375em)"
        height: 432
        width: 1200
      source_med5:
        media: "(min-width: 40em) and (max-width: 41.9375em)"
        height: 432
        width: 1200
      source_med6:
        media: "(min-width: 38em) and (max-width: 39.9375em)"
        height: 432
        width: 1200
      source_med7:
        media: "(min-width: 33em) and (max-width: 37.9375em)"
        height: 432
        width: 1200
      source_med8:
        media: "(min-width: 28em) and (max-width: 32.9375em)"
        height: 216
        width: 600
      source_med9:
        media: "(min-width: 21em) and (max-width: 27.9375em)"
        height: 216
        width: 600
      source_default:
        height: 108
        width: 320      
   # Half width pictures such as tiles
    half:
      ppi: [1, 1.5, 2]
      attr:
        data-active: nil
      source_med:
        media: "(min-width: 24.625em)"
        width: 368
      source_default:
        width: 184
    # Half width pictures such as tiles
    tile:
      ppi: [1, 1.5, 2]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_med:
        media: "(min-width: 24.625em)"
        height: 168
        width: 368
      source_default:
        height: 84      
        width: 184        
    # Golden width pictures
    golden:
      ppi: [1, 1.5, 2]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_med:
        media: "(min-width: 54em)"
        width: 384
      source_med1:
        media: "(min-width: 40em) and (max-width: 53.9375em)"
        width: 384
      source_med2:
        media: "(min-width: 30em) and (max-width: 39.9375em)"
        width: 221
      source_med3:
        media: "(min-width: 25em) and (max-width: 29.9375em)"
        width: 464
      source_med4:
        media: "(min-width: 21em) and (max-width: 24.9375em)"
        width: 384
      source_default:
        width: 320    
    # Fourth width pictures
    fourth:
      ppi: [1, 1.5, 2]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_med:
        media: "(min-width: 53em)"
        width: 154
      source_med1:
        media: "(min-width: 40em) and (max-width: 52.9375em)"
        width: 112
      source_med2:
        media: "(min-width: 30em) and (max-width: 39.9375em)"
        width: 142
      source_med3:
        media: "(min-width: 21em) and (max-width: 29.9375em)"
        width: 222
      source_default:
        width: 154 
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250
